export * from './ArmazenamentoSection'
export * from './CompartilhamentoSection'
export * from './ConsentimentoSection'
export * from './DadosSection'
export * from './DireitosSection'
export * from './FinalidadeSection'
export * from './RetencaoSection'
export * from './TransferenciaSection'
